-- 코드를 입력하세요
SELECT info.REST_ID, info.REST_NAME, info.FOOD_TYPE, info.FAVORITES, info.ADDRESS, ROUND(AVG(re.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS info, REST_REVIEW AS re
WHERE info.REST_ID = re.REST_ID AND info.ADDRESS LIKE '서울%'
GROUP BY info.REST_ID
ORDER BY SCORE DESC, info.FAVORITES DESC;